name: Java Deployment Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml clean package
      - name: Show contents of the current working directory
        run: ls -la
      - name: Show contents of the target directory
        run: ls -la target
      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: ./target/hng-java-boilerplate-0.0.1-SNAPSHOT.jar

  unit-test:
    needs: build
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Install Dependencies
        run: mvn dependency:go-offline
      - name: Unit Testing
        run: mvn -B test
      - name: Archive Test Result
        uses: actions/upload-artifact@v3
        if: always()
        with: 
          name: artifact
          path: target


  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: List Available Artifacts
        run: echo "${{ toJson(github.workspace.artifact) }}"
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact 
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
      - name: Add SSH Key to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
    
      - name: Deploy and Run Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST \
            sudo apt install -y openjdk-17-jdk
            export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
            echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
            cd /home/dhee/
            sudo nohup java -jar hng-java-boilerplate-0.0.1-SNAPSHOT.jar &